### ISSUE TITLE
Not yet perfect

### ISSUE THREAD

**Issue by JimmyChu2** [TheKonka/instagram-download-browser-extension#15]
And - I suspect - not likely to ever be.... I don't know where you're at physically, but in the US, we sometimes talk of whack-a-mole. You can look it up, but it basically relates to situations (I'm sure this is ONE SUCH) where no sooner do you provide something USEFUL ... but which Instagram HATES ... than they do something to make it fail. I'm glad I installed it and it definitely works some of the time. You have a screenshot of an Asian girl, and her images download beautifully. Here's my "fail" - https://www.instagram.com/frankinjection/p/CwAb4TEoRE_/?img_index=1

I tried it on both Chrome & Firefox & no down arrow appears. Feel free to email me at peter [at] mossandfreud.com

Very minor thing. The extension name on Chrome & Firefox is different. Maybe, you cannot control that, but if you can, you should. You have the makings of a beautiful brand AND a great product! (I'm using it to collect some great photos of Prague, and it's working great on at least one of those.)

**Comment by TheKonka** [comment]
I have searched whack-a-mole, you are right, I have to keep the extension updated when Instagram change their pages or api. 

> https://www.instagram.com/frankinjection/p/CwAb4TEoRE_/?img_index=1

The reason why the extension doesn't work at this link is that I have't encountered a post detail url with a username in it 🤷‍♀️. Usually when I open a post from the user profile page, there is no username in the url. So I didn't write code to be compatible with this situation. But because of your feedback, this problem has been fixed in the latest version(1.5.0).

As for why the extension name on Chrome & Firefox is different, well, they are same from the beginning and that's what I want. But on Chrome, it was taken down by the complaint from Instagram, so I had no choice but to put a different name on it.
Luckily, there weren't too many complaints on Firefox. 
![image](https://github.com/TheKonka/instagram-download-browser-extension/assets/22173084/e05de5b6-8634-4486-b0d1-7d14eff74f0d)
I wanted to keep the same name, but I couldn't think of anything related to Instagram downloads that wouldn't get complaints.

**Comment by JimmyChu2** [comment]
THANK you so very much.... Your English is so extraordinarily excellent
that I have to think that you either have an English-speaking parent ... or
you're amazing at languages ... or translation software has gone from
awfully ragged to first rate in 40 (?) years.

But mostly, I'm impressed that you solved it (and "published") so very
quickly. You have a great deal to be proud of with this extension. Whoever
employs you is very fortunate to have someone so good on their staff!!

There seem to be at least 2 other similar extensions out there, and it
occurs to me that they - which also didn't work on my target site - may not
be as bad as I thought they were. You're right about its being tough to
operate in a world where Instagram can certainly make life difficult for
people like you - in at least 2 ways. It's also the case that, I'm sure,
"reviews" are pretty arbitrary. I think at least 1 person each said that
those 2 extensions were "garbage." That's why I - fortunately - looked even
harder and found yours!

ONE of the 2 alternative extensions has a nice feature you might be
interested in replicating. They provide a single down-arrow as you do, but
the other author also has an icon with 3 such arrows next to one another,
and ITS function is to download ALL the images in a given "reel." I've done
enough coding to know that "easy to say" is often very far from "easy to
do," but my "experience" with you and what turned out to be a minor bug is
such that I imagine you could accomplish this in no more than an hour or 2.

AGAIN, thanks ... and a very happy & healthy 2024 to you!

-JC

**Comment by JimmyChu2** [comment]
I may have to take back some of my praise. That is - YOU WERE FAST, ... but
either Instagram is even faster (VERY UNLIKELY) or you missed something.

With both Firefox & Chrome - a different machine, so there can be no
question of my using something other than 1.5 - one gets "download failed"
when clicking on your arrow on the site in question:

Prague is really one of the most beautiful & picturesque cities in the
world. I was stoked to be back and have some downtime to explore… |
Instagram
<https://www.instagram.com/frankinjection/p/CwAb4TEoRE_/?img_index=1>

I hope you CAN fix this, of course. I'll be looking for an email from you
to that effect, but please - DO TEST any patch you think addresses the
issue.

**Comment by TheKonka** [comment]
[rs-1704718354140-664057249.webm](https://github.com/TheKonka/instagram-download-browser-extension/assets/22173084/c0770702-b347-4328-848d-2d65cc29f58b)

This is strange. I can download the media without any errors. 🤷‍♀️
I can only suspect that the page structure is different for different users.
For the time being, you can try to see if you can save the image by right clicking on it.
I'll try to fix the problem later.

**Comment by nodeOfCode** [comment]
Any idea why it won't work on the following:  https://www.instagram.com/philsnelgrove/reel/B5GeRJoBAc1/

Works as expected on the link in the OP, so the plugin is definitely enabled.

**Comment by TheKonka** [comment]
> Any idea why it won't work on the following: https://www.instagram.com/philsnelgrove/reel/B5GeRJoBAc1/
> 
> Works as expected on the link in the OP, so the plugin is definitely enabled.

The reason is similar to the above, I haven't tested the reel page with username on the route.
This issue has been fixed in latest version (1.5.1) . Thanks for the feedback!
The chrome version has been updated, the Firefox version is still under review.

**Comment by nodeOfCode** [comment]
Appreciated, looking forward to the update!
